version: "3.7"

# x-extension fields
x-env_file: &env_file
  env_file:
    - ./.env

services:
  backend:
    <<: *env_file
    container_name: finkybotz_api
    command: uvicorn --host=0.0.0.0 --port 8000 app.main:app --reload
    build:
      context: .
      dockerfile: docker/Dockerfile.api
      args:
        REQUIREMENTS: ${REQUIREMENTS:-dev}
    ports:
      - 8000:8000
    depends_on:
      - mssql
    restart: always
    volumes:
      - ./app/:/src/app
      - ./database_interface/:/src/database_interface
      - ./database_interface/alembic.ini:/src/alembic.ini
    tty: true
    stdin_open: true

  tests:
    <<: *env_file
    container_name: finkybotz_tests
    command: pytest -v tests -s
    build:
      context: .
      dockerfile: docker/Dockerfile.tests
      network: host
#    env_file:
#      - .env.tests
    depends_on:
      - mssql
    profiles:
      - tests
    volumes:
      - .:/src

  mssql:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    <<: *env_file
    ports:
      - 1433:1433
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data:
