FROM python:3.10-slim-buster

WORKDIR /src

ENV PYTHONUNBUFFERED=1 PIP_NO_CACHE_DIR=1 PIP_DISABLE_PIP_VERSION_CHECK=1

RUN apt-get -y update --allow-releaseinfo-change && apt-get install curl gnupg -y && \
    curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - && \
    curl https://packages.microsoft.com/config/debian/10/prod.list > /etc/apt/sources.list.d/mssql-release.list && \
    apt-get -y update --allow-releaseinfo-change && ACCEPT_EULA=Y apt-get install gcc libpq-dev build-essential libssl-dev uuid-dev cmake libcurl4-openssl-dev pkg-config python3-dev python3-pip msodbcsql17 mssql-tools unixodbc unixodbc-dev -y

COPY app/requirements/dev.txt /src/dev_app.txt

RUN pip install --no-cache-dir --upgrade -r /src/dev_app.txt

COPY . /src

RUN chmod 755 load_env.sh
# CMD export Database=Test && echo $Database && pytest