name: Build and test on develop

on:
  push:
    branches: []
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: []

env:
  REGISTRY: ghcr.io
  SA_PW: MSSQLpassword1

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
#      - name: Log in to GitHub Packages
#        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${REGISTRY} -u ${{ github.actor }} --password-stdin
#      - name: Pull image
#        run: |
#          docker pull ${{ env.TEST_IMAGE_NAME }} || true
      - name: Install SQL Server
        shell: bash
        run: |
          docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=${{ env.SA_PW }}" -e "MSSQL_PID=Developer" -e "MSSQL_COLLATION=Polish_CI_AI" -p 1433:1433 --name sqlserver -d mcr.microsoft.com/mssql/server:2019-latest
      - name: Check docker
        shell: bash
        run: |
          docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' sqlserver
      - name: Build container
        run: |
          docker build \
          -f docker/Dockerfile.tests \
          -t finkybotz-tests \
          "."
      - name: Setup SQL Server
        run: docker exec sqlserver bash -c "/opt/mssql-tools/bin/sqlcmd -S 127.0.0.1,1433 -U sa -P ${{ env.SA_PW }} -Q 'CREATE DATABASE test_database COLLATE Polish_CI_AI'"
      - name: Run tests
        run: |
          docker run \
          --name finkybotz-tests \
          --env-file=.env.test.docker \
          finkybotz-tests \
          bash -c pytest -v -s
