name: Build and test on develop

on:
  push:
    branches: []
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: []

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  TEST_IMAGE_NAME: ${REGISTRY}/${IMAGE_NAME}/finkybotz-tests

jobs:
  test:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Log in to GitHub Packages
        run: echo ${GITHUB_TOKEN} | docker login -u ${GITHUB_ACTOR} --password-stdin ${REGISTR}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull image
        run: |
          docker pull ${TEST_IMAGE_NAME} || true