name: Build and test on develop

on:
  push:
    branches: []
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: []

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  TEST_IMAGE_NAME: ${REGISTRY}/${IMAGE_NAME}/finkybotz-tests

jobs:
  test:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Log in to GitHub Packages
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Pull image
        run: |
          docker pull $TEST_IMAGE_NAME || true